baseURL = "https://sa2c.github.io/RSE-handbook/"
title = 'RSE Handbook'
theme = 'book'

languageCode = 'en-gb'

# Enable last modified date on doc pages
enableGitInfo = true

# Enable Emoji emoticons support for page content; see emoji-cheat-sheet.com
enableemoji = true

# The Book theme doesn't render taxonomy, remove related files
disableKinds = ['taxonomy', 'taxonomyTerm']

# Extra menu items
[menu]
# Before ToC
#[[menu.before]]

# After ToC
[[menu.after]]
  name = 'Swansea Academy of Advanced Computing (SA2C)'
  url = 'https://www.swansea.ac.uk/compsci/swansea-academy-of-advanced-computing-sa2c/'
  weight = 10
  
[[menu.after]]
  name = 'Supercomputing Wales'
  url = 'https://www.supercomputing.wales/'
  weight = 11

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  # Automatically select from dark and light themes based on browser/os preferences
  BookTheme = 'auto'

  # Show page ToC on the right side of pages
  BookToC = true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/sa2c/RSE-handbook'

  # Path to commits in repository
  # URL is constructed as <BookRepo>/<BookCommitPath>/<commit-hash>
  # Github uses 'commit'
  BookCommitPath = 'commit'

  # Enable 'Edit this page' link. Requires 'BookRepo' param.
  # URL is constructed as <BookRepo>/<BookEditPath>/<path to file>
  # Github users 'edit/<branch name>'
  BookEditPath = 'edit/main'

  # Configure the date format used on the pages.
  # See https://gohugo.io/functions/format/#gos-layout-string for information
  BookDateFormat = '2 Jan 2006'

  # Enable search
  BookSearch = true
